=== lnikiniki/hw8/src/main/java/com/epam/lab/hw8/candy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="candies" type="candies"/>

    <xsd:complexType name="candies">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="candy" type="candy"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="candy">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="type" type="type"/>
            <xsd:element name="energy" type="xsd:decimal"/>
            <xsd:element name="ingredients" type="ingredients"/>
            <xsd:element name="value" type="value"/>
            <xsd:element name="production" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:simpleType name="type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="chocolate"/>
            <xsd:enumeration value="waffle"/>
            <xsd:enumeration value="jelly"/>
            <xsd:enumeration value="caramel"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="ingredients">
        <xsd:sequence>
            <xsd:element name="sugar" type="xsd:decimal"/>
            <xsd:element name="chocolate" type="chocolate"/>
            <xsd:element name="ingredient" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="value">
        <xsd:sequence>
            <xsd:element name="protein" type="xsd:decimal"/>
            <xsd:element name="fat" type="xsd:decimal"/>
            <xsd:element name="carbohydrates" type="xsd:decimal"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="chocolate">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="milk"/>
            <xsd:enumeration value="dark"/>
            <xsd:enumeration value="white"/>
            <xsd:enumeration value="no"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== lnikiniki/hw8/src/main/java/com/epam/lab/hw8/candy.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="candy.xsd">
    <candy>
        <name>Snickers</name>
        <type>chocolate</type>
        <energy>487</energy>
        <ingredients>
            <sugar>20</sugar>
            <chocolate>milk</chocolate>
            <ingredient>peanuts</ingredient>
        </ingredients>
        <value>
            <protein>9</protein>
            <fat>28.2</fat>
            <carbohydrates>55</carbohydrates>
        </value>
        <production>Mars</production>
    </candy>
    <candy>
        <name>Kinder Chocolate</name>
        <type>chocolate</type>
        <energy>562</energy>
        <ingredients>
            <sugar>15</sugar>
            <chocolate>milk</chocolate>
            <ingredient>cocoa</ingredient>
        </ingredients>
        <value>
            <protein>8.7</protein>
            <fat>34.8</fat>
            <carbohydrates>53.5</carbohydrates>
        </value>
        <production>Ferrero</production>
    </candy>
    <candy>
        <name>Raffaello</name>
        <type>waffle</type>
        <energy>623</energy>
        <ingredients>
            <sugar>35</sugar>
            <chocolate>no</chocolate>
            <ingredient>almond</ingredient>
        </ingredients>
        <value>
            <protein>9.3</protein>
            <fat>47.8</fat>
            <carbohydrates>38.8</carbohydrates>
        </value>
        <production>Ferrero</production>
    </candy>
    <candy>
        <name>Bonny-Fruit</name>
        <type>jelly</type>
        <energy>320</energy>
        <ingredients>
            <sugar>66</sugar>
            <chocolate>no</chocolate>
            <ingredient>concentrated juices</ingredient>
        </ingredients>
        <value>
            <protein>0.1</protein>
            <fat>0</fat>
            <carbohydrates>80</carbohydrates>
        </value>
        <production>Roshen</production>
    </candy>
</candies>
